### ISSUE TITLE
Ventable loose configuration in Guard/spring rspec

### ISSUE THREAD

**Issue by anfinil** [kigster/ventable#4]
I'm using `guard` gem to speed up testing. Guard runs specs using `spring rspec`. When I change something in app code ventable notifications stop working. Seems that problem is that when spring reloads event classes `ventable` configuration is no more actual.

**Comment by kigster** [comment]
You probably just need to make sure that your event initializer is reloaded upon class reload. I'm sure you can register with spring a specific block or a file to be reloaded. 

By default in rails gems and lob folder aren't reloaded. So if your event initializer is registering class level dependencies they won't work after these classes reload.
